services:

  db:
    image: postgres:14
    container_name: project_devops
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: devops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: hertin12/projet_devops:latest
    container_name: devops_project
    ports:
      - "5000:5000"
    environment:
      DOCKER_ENV: true
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_HOST: db              # ← Nom du service dans docker-compose
      DB_PORT: "5432"
      DB_NAME: devops_db
      SECRET_KEY: 28f218fd66fbffb35db4dff88b9628d1a88fa17856f22c9fe811b01bed614ea0304e3bef8cbcddf39084898378af8cd5b2e406e82d6269c067ef95e1ec0bf038
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:admin@db:5432/devops_db
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: